ci: update workflow crowdin-upload-pot

diff --git a/.github/workflows/ci-crowdin-upload-pot.yml b/.github/workflows/ci-crowdin-upload-pot.yml
--- a/.github/workflows/ci-crowdin-upload-pot.yml
+++ b/.github/workflows/ci-crowdin-upload-pot.yml
@@ -32,7 +32,42 @@ on:
           - 'v3'
 
 jobs:
+  check-secrets-and-vars:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]; then
+            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [ "$SECRETS_EXIST" = "false" ]; then
+            exit 1
+          fi
+      - name: Check Variables
+        shell: bash
+        run: |
+          VARIABLES_EXIST=true
+          if [ -z "${{ vars.ACTOR_ID }}" ]; then
+            echo "vars.ACTOR_ID is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_NAME }}" ]; then
+            echo "vars.ACTOR_NAME is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_LOGIN }}" ]; then
+            echo "vars.ACTOR_LOGIN is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ "$VARIABLES_EXIST" = "false" ]; then
+            exit 1
+          fi
+
   pr-merged:
+    needs: [ 'check-secrets-and-vars' ]
     if: ( github.event_name == 'repository_dispatch' && 
           github.event.action == 'pr-merged' &&
           github.event.client_payload.CROWDIN == 'true' )
@@ -45,9 +80,11 @@ jobs:
       CHECKOUT: 'refs/heads/source'
       VERSION: ${{ github.event.client_payload.VERSION }}
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
 
   get-matrix:
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' )
@@ -81,8 +118,8 @@ jobs:
           echo "${VERSION_LIST}" | jq "."
 
   matrix:
+    needs: [ 'check-secrets-and-vars', 'get-matrix' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' )
-    needs: get-matrix
     concurrency:
       group: ${{ github.workflow }}-${{ matrix.VERSION }}
       cancel-in-progress: true
@@ -96,11 +133,14 @@ jobs:
       CHECKOUT: ${{ github.ref }}
       VERSION: ${{ matrix.VERSION }}
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
 
   single:
+    needs: [ 'check-secrets-and-vars' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
     concurrency:
       group: ${{ github.workflow }}-${{ inputs.VERSION }}
@@ -111,6 +151,8 @@ jobs:
       CHECKOUT: ${{ github.ref }}
       VERSION: ${{ inputs.VERSION }}
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
