ci: update workflow crowdin-document

diff --git a/.github/workflows/ci-crowdin-document.yml b/.github/workflows/ci-crowdin-document.yml
--- a/.github/workflows/ci-crowdin-document.yml
+++ b/.github/workflows/ci-crowdin-document.yml
@@ -23,7 +23,46 @@ on:
         default: 'all'
 
 jobs:
+  check-secrets-and-env:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Secrets
+        id: check_secrets
+        run: |
+          SECRETS_EXIST=true
+          if [ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing"
+            SECRETS_EXIST=false
+          fi
+          if [ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]; then
+            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing"
+            SECRETS_EXIST=false
+          fi
+          echo "SECRETS_EXIST=$SECRETS_EXIST" >> ${GITHUB_OUTPUT}
+      - name: Check Environment Variables
+        id: check_envvars
+        run: |
+          ENVVARS_EXIST=true
+          if [ -z "${{ env.ACTOR_ID }}" ]; then
+            echo "env.ACTOR_ID is missing"
+            ENVVARS_EXIST=false
+          fi
+          if [ -z "${{ env.ACTOR_NAME }}" ]; then
+            echo "env.ACTOR_NAME is missing, but it's optional"
+          fi
+          echo "ENVVARS_EXIST=$ENVVARS_EXIST" >> $GITHUB_OUTPUT
+      - name: Summarize check results
+        run: |
+          if [ "${{ steps.check_secrets.outputs.SECRETS_EXIST }}" = "false" ] || \
+             [ "${{ steps.check_envvars.outputs.ENVVARS_EXIST }}" = "false" ]; then
+            echo "One or more secrets/env variables are missing."
+            exit 1
+          else
+            echo "All secrets and environment variables are set correctly!"
+          fi
+
   single:
+    needs: [ 'check-secrets-and-env' ]
     if: ( github.event_name == 'push' ) ||
         ( github.event_name == 'schedule' ) ||
         ( github.event_name == 'workflow_dispatch' )
