ci: update workflow crowdin-download-po

diff --git a/.github/workflows/ci-crowdin-download-po.yml b/.github/workflows/ci-crowdin-download-po.yml
--- a/.github/workflows/ci-crowdin-download-po.yml
+++ b/.github/workflows/ci-crowdin-download-po.yml
@@ -47,6 +47,44 @@ env:
   CRON_V3: '0 0 1,15 * *'
 
 jobs:
+  check-secrets-and-vars:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [ -z "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" ]; then
+            echo "secrets.CROWDIN_PERSONAL_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [ "$SECRETS_EXIST" = "false" ]; then
+            exit 1
+          fi
+      - name: Check Variables
+        shell: bash
+        run: |
+          VARIABLES_EXIST=true
+          if [ -z "${{ vars.ACTOR_ID }}" ]; then
+            echo "vars.ACTOR_ID is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_NAME }}" ]; then
+            echo "vars.ACTOR_NAME is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_LOGIN }}" ]; then
+            echo "vars.ACTOR_LOGIN is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ "$VARIABLES_EXIST" = "false" ]; then
+            exit 1
+          fi
+
   get-matrix:
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
         ( github.event_name == 'schedule' )
@@ -94,9 +132,9 @@ jobs:
           echo "${LANGUAGE_LIST}" | jq "."
 
   matrix:
+    needs: [ 'check-secrets-and-vars', 'get-matrix' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
         ( github.event_name == 'schedule' )
-    needs: get-matrix
     concurrency:
       group: ${{ github.workflow }}-${{ matrix.VERSION }}
       cancel-in-progress: true
@@ -114,11 +152,15 @@ jobs:
       MODE_OF_UPDATE: ${{ inputs.MODE_OF_UPDATE || 'COMPARE' }}
       CALLER_JOB: 'matrix (${{ matrix.VERSION }}, ${{ matrix.LANGUAGE }})'
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
+      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
 
   single:
+    needs: [ 'check-secrets-and-vars' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
     concurrency:
       group: ${{ github.workflow }}-${{ inputs.VERSION }}
@@ -132,6 +174,9 @@ jobs:
       MODE_OF_UPDATE: ${{ inputs.MODE_OF_UPDATE }}
       CALLER_JOB: 'single'
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
+      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
