ci: update workflow gettext-update-po

diff --git a/.github/workflows/ci-gettext-update-po.yml b/.github/workflows/ci-gettext-update-po.yml
--- a/.github/workflows/ci-gettext-update-po.yml
+++ b/.github/workflows/ci-gettext-update-po.yml
@@ -52,11 +52,45 @@ on:
           - 'NEVER'
 
 jobs:
+  check-secrets-and-vars:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Secrets
+        shell: bash
+        run: |
+          SECRETS_EXIST=true
+          if [ -z "${{ secrets.ACTOR_GITHUB_TOKEN }}" ]; then
+            echo "secrets.ACTOR_GITHUB_TOKEN is missing."
+            SECRETS_EXIST=false
+          fi
+          if [ "$SECRETS_EXIST" = "false" ]; then
+            exit 1
+          fi
+      - name: Check Variables
+        shell: bash
+        run: |
+          VARIABLES_EXIST=true
+          if [ -z "${{ vars.ACTOR_ID }}" ]; then
+            echo "vars.ACTOR_ID is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_NAME }}" ]; then
+            echo "vars.ACTOR_NAME is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ -z "${{ vars.ACTOR_LOGIN }}" ]; then
+            echo "vars.ACTOR_NAME is missing."
+            VARIABLES_EXIST=false
+          fi
+          if [ "$VARIABLES_EXIST" = "false" ]; then
+            exit 1
+          fi
+
   pr-merged:
+    needs: [ 'check-secrets-and-vars' ]
     if: ( github.event_name == 'repository_dispatch' && 
           github.event.action == 'pr-merged' &&
           github.event.client_payload.GETTEXT == 'true' )
-    secrets: inherit
     concurrency:
       group: ${{ github.workflow }}-${{ github.event.client_payload.VERSION }}
       cancel-in-progress: true
@@ -69,8 +103,11 @@ jobs:
       MODE_OF_UPDATE: 'ALWAYS'
       CALLER_JOB: 'pr-merged'
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
 
   get-matrix:
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' )
@@ -104,8 +141,8 @@ jobs:
           echo "${VERSION_LIST}" | jq "."
 
   matrix:
+    needs: [ 'check-secrets-and-vars', 'get-matrix' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' )
-    needs: get-matrix
     concurrency:
       group: ${{ github.workflow }}-${{ matrix.VERSION }}-${{ matrix.LANGUAGE }}
       cancel-in-progress: true
@@ -123,11 +160,14 @@ jobs:
       MODE_OF_UPDATE: ${{ inputs.MODE_OF_UPDATE || 'COMPARE' }}
       CALLER_JOB: 'matrix (${{ matrix.VERSION }}, ${{ matrix.LANGUAGE }})'
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
 
   single:
+    needs: [ 'check-secrets-and-vars' ]
     if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
     concurrency:
       group: ${{ github.workflow }}-${{ inputs.VERSION }}-${{ inputs.LANGUAGE }}
@@ -141,6 +181,8 @@ jobs:
       MODE_OF_UPDATE: ${{ inputs.MODE_OF_UPDATE }}
       CALLER_JOB: 'single'
       ENABLE_JOB: true
-      ACTOR_ID: '178366084'
-      ACTOR_NAME: 'ltdrobot'
-    secrets: inherit
+      ACTOR_ID: ${{ vars.ACTOR_ID }}
+      ACTOR_NAME: ${{ vars.ACTOR_NAME }}
+      ACTOR_LOGIN: ${{ vars.ACTOR_LOGIN }}
+    secrets:
+      ACTOR_GITHUB_TOKEN: ${{ secrets.ACTOR_GITHUB_TOKEN }}
